Training data: 360
Validation data: 240
input_samples (?, 32000)
input_samples_reshape (?, 32000, 1)
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
3D Conv Out: (?, 50, 32, 32, 64)
3D Conv Out Reshape: (?, 32, 32, 64)
Resnet18 Out: (?, 1, 1, 512)
Resnet18 Linear Out: (?, 256)
Input to GRU: (?, 50, 256)
GRU Out: (?, 50, 29)
ResNet LSTM Pretrain weights loaded
outv: (?, 200, 256)
outa: (?, 200, 256)
attn_out: (?, 200, 256)
attn_states: (?, 200, 200)
fusion: (?, 200, 512)
Phase (?, 257, 200, 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 200 and 257 for 'mul' (op: 'Mul') with input shapes: [?,200,257,2], [?,257,200,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_tasnet.py", line 90, in <module>
    tasnet = TasNet(video_ip_shape=(50,50,100,3), time_dimensions=200, frequency_bins=257, n_frames=50, lipnet_pretrained='pretrain',  train_lipnet=None)
  File "/data/AV-speech-separation1/models/tasnet_pred_samples.py", line 72, in __init__
    self.build()
  File "/data/AV-speech-separation1/models/tasnet_pred_samples.py", line 178, in build
    self.mag_phase_mul_spect = self.audio_input * self.mag_phase
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 812, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 1078, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 5860, in mul
    "Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 200 and 257 for 'mul' (op: 'Mul') with input shapes: [?,200,257,2], [?,257,200,1].
